<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laporan Retur</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='4' height='4' viewBox='0 0 4 4'%3E%3Cpath fill='%23ced4da' fill-opacity='0.4' d='M1 3h1v1H1V3zm2-2h1v1H3V1z'%3E%3C/path%3E%3C/svg%3E");
        }

        table {
            width: 100%;
            border-collapse: collapse;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        th, td {
            padding: 12px 15px;
            text-align: left;
            border: 1px solid #ddd;
        }

        th {
            background-color: #007bff;
            color: white;
            font-weight: bold;
            border-bottom: 2px solid #0056b3;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #e0f7fa;
        }

        h2 {
            color: #007bff;
            text-align: center;
        }

        footer {
            margin-top: 20px;
            text-align: center;
            font-size: 12px;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <h2>Laporan Retur</h2>
    <table>
        <thead>
            <tr>
                <th>Nama Supplier</th>
                <th>Kode Jenis Bahan Baku</th>
                <th>Total Retur</th>
                <th>Total Pembelian</th>
                <th>Total Stok</th>
                <th>Total Retur Value</th>
                <th>Average Retur Quantity</th>
                <th>Return Rate (%)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $item)
                <tr>
                    <td>{{ $item->nama_supplier }}</td>
                    <td>{{ $item->KodeJenisBahanBaku }}</td>
                    <td>{{ $item->total_retur }}</td>
                    <td>{{ $item->total_pembelian }}</td>
                    <td>{{ $item->total_stok }}</td>
                    <td>{{ number_format($item->total_retur_value, 0, ',', '.') }}</td>
                    <td>{{ number_format($item->avg_retur_quantity, 2, ',', '.') }}</td>
                    <td>{{ number_format($item->return_rate, 2, ',', '.') }}%</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <footer>
        <p>Generated by {{ config('app.name') }} on {{ now()->format('d-m-Y H:i:s') }}</p>
        <p>&copy; {{ date('Y') }} {{ config('app.name') }}. All rights reserved.</p>
        <p>Total Suppliers: {{ $data->count() }}</p>
        <p>Total Retur: {{ $data->sum('total_retur') }}</p>
        <p>Total Pembelian: {{ $data->sum('total_pembelian') }}</p>
        <p>Total Stok: {{ $data->sum('total_stok') }}</p>
        <p>Average Return Rate: {{ number_format($data->avg('return_rate'), 2, ',', '.') }}%</p>
        <p>Highest Return Rate: {{ number_format($data->max('return_rate'), 2, ',', '.') }}%</p>
        <p>Lowest Return Rate: {{ number_format($data->min('return_rate'), 2, ',', '.') }}%</p>
    </footer>
</body>
</html>