<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Analisis Stok Bahan Baku</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='4' height='4' viewBox='0 0 4 4'%3E%3Cpath 1  fill='%23ced4da' fill-opacity='0.4' d='M1 3h1v1H1V3zm2-2h1v1H3V1z'%3E%3C/path%3E%3C/svg%3E");
        }

        table {
            width: 100%;
            border-collapse: collapse;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px; 
        }

        th, td {
            padding: 12px 15px;
            text-align: left;
            border: 1px solid #ddd;
        }

        th {
            background-color: #007bff;
            color: white;
            font-weight: bold;
            border-bottom: 2px solid #0056b3;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #e0f7fa;
        }

        h2 {
            color: #007bff;
            text-align: center;
        }

        footer {
            margin-top: 20px;
            text-align: center;
            font-size: 12px;
            color: #6c757d;
        }

        .warning {
            color: #dc3545; 
            font-weight: bold;
        }

        .summary { 
            background: white;
            padding: 15px;
            margin: 10px 0;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .summary h3 {
            color: #007bff; 
        }
    </style>
</head>
<body>
    <h2>Analisis Stok dan Penggunaan Bahan Baku</h2>

    <div class="metric-card">
        <table>
            <thead>
                <tr>
                    <th>Kode Bahan</th>
                    <th>Nama Bahan</th>
                    <th>Jenis</th>
                    <th>Stok Saat Ini</th>
                    <th>Total Transaksi Pemakaian</th>
                    <th>Total Pemakaian</th>
                    <th>Status Stok</th> 
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td>{{ $item->KodeBahanBaku }}</td>
                    <td>{{ $item->NamaBahanBaku }}</td>
                    <td>{{ $item->JenisBahanBaku }}</td>
                    <td>{{ number_format($item->current_stock) }}</td>
                    <td>{{ number_format($item->usage_count) }}</td>
                    <td>{{ number_format($item->total_usage) }}</td>
                    <td> 
                        @if($item->current_stock < 100) 
                            <span class="warning">Stok Rendah</span>
                        @else
                            Normal
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="summary">
        <h3>Ringkasan Stok:</h3>
        <p>Total Jenis Bahan: {{ $data->count() }}</p>
        <p>Total Stok Keseluruhan: {{ number_format($data->sum('current_stock')) }}</p>
        <p>Total Pemakaian: {{ number_format($data->sum('total_usage')) }}</p> 
        <p>Bahan Stok Rendah: {{ $data->where('current_stock', '<', 100)->count() }}</p> 
    </div>

    <footer>
        <p>Generated by {{ config('app.name') }} on {{ now()->format('d-m-Y H:i:s') }}</p>
        <p>&copy; {{ date('Y') }} {{ config('app.name') }}. All rights reserved.</p>
    </footer>
</body>
</html>