<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchase Analysis Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='4' height='4' viewBox='0 0 4 4'%3E%3Cpath fill='%23ced4da' fill-opacity='0.4' d='M1 3h1v1H1V3zm2-2h1v1H3V1z'%3E%3C/path%3E%3C/svg%3E");
        }

        table {
            width: 100%;
            border-collapse: collapse;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px; /* Add spacing between tables */
        }

        th, td {
            padding: 12px 15px;
            text-align: left;
            border: 1px solid #ddd;
        }

        th {
            background-color: #007bff;
            color: white;
            font-weight: bold;
            border-bottom: 2px solid #0056b3;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #e0f7fa;
        }

        h2 {
            color: #007bff;
            text-align: center;
        }

        footer {
            margin-top: 20px;
            text-align: center;
            font-size: 12px;
            color: #6c757d;
        }

        .warning { /* You can add this class for future use */
            color: #dc3545;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h2>Purchase Analysis Report</h2>
    <table>
        <thead>
            <tr>
                <th>Supplier Name</th>
                <th>Material Type</th>
         
                <th>Total Quantity</th>
                <th>Total Value</th>
                <th>Average Price</th>
                <th>Purchase Month</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $analysis)
            <tr>
                <td>{{ $analysis->nama_supplier }}</td>
                <td>{{ $analysis->JenisBahanBaku }}</td>

                <td>{{ $analysis->total_quantity }}</td>
                <td>{{ number_format($analysis->total_value, 0, ',', '.') }}</td>
                <td>{{ number_format($analysis->avg_price, 0, ',', '.') }}</td>
                <td>{{ $analysis->purchase_month }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <footer>
        <p>Generated by {{ config('app.name') }} on {{ now()->format('d-m-Y H:i:s') }}</p>
        <p>&copy; {{ date('Y') }} {{ config('app.name') }}. All rights reserved.</p>
        <p>Total Transactions: {{ $data->count() }}</p>
        <p>Total Purchase Value: Rp {{ number_format($data->sum('total_value'), 0, ',', '.') }}</p>
        <p>Total Quantity Purchased: {{ $data->sum('total_quantity') }}</p>
        <p>Average Purchase Value: Rp {{ number_format($data->avg('total_value'), 0, ',', '.') }}</p>
    </footer>
</body>
</html>