<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Analisis Performa Supplier</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='4' height='4' viewBox='0 0 4 4'%3E%3Cpath 1  fill='%23ced4da' fill-opacity='0.4' d='M1 3h1v1H1V3zm2-2h1v1H3V1z'%3E%3C/path%3E%3C/svg%3E");
        }

        table {
            width: 100%;
            border-collapse: collapse;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px; 
        }

        th, td {
            padding: 12px 15px;
            text-align: left;
            border: 1px solid #ddd;
        }

        th {
            background-color: #007bff;
            color: white;
            font-weight: bold;
            border-bottom: 2px solid #0056b3;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #e0f7fa;
        }

        h2 {
            color: #007bff;
            text-align: center;
        }

        footer {
            margin-top: 20px;
            text-align: center;
            font-size: 12px;
            color: #6c757d;
        }

        .warning {
            color: #dc3545; 
            font-weight: bold;
        }

        .summary { 
            background: white;
            padding: 15px;
            margin: 10px 0;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .summary h3 {
            color: #007bff; 
        }
    </style>
</head>
<body>
    <h2>Analisis Performa Supplier</h2>

    <div class="metric-card">
        <h3>Performa Supplier Detail</h3> 
        <table>
            <thead>
                <tr>
                    <th>Kode</th>
                    <th>Nama Supplier</th>
                    <th>Total Transaksi</th>
                    <th>Total Pembelian</th>
                    <th>Total Nilai Pembelian (Rp)</th>
                    <th>Total Retur</th>
                    <th>Total Nilai Retur (Rp)</th>
                    <th>Rate Retur (%)</th>
                    <th>Dampak Finansial (%)</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $supplier)
                <tr>
                    <td>{{ $supplier['kode_supplier'] }}</td>
                    <td>{{ $supplier['nama_supplier'] }}</td>
                    <td>{{ number_format($supplier['purchase_count']) }}</td>
                    <td>{{ number_format($supplier['total_purchases']) }}</td>
                    <td>{{ number_format($supplier['total_purchase_value']) }}</td>
                    <td>{{ number_format($supplier['total_returns']) }}</td>
                    <td>{{ number_format($supplier['total_return_value']) }}</td>
                    <td>{{ number_format($supplier['return_rate'], 2) }}</td>
                    <td>{{ number_format($supplier['financial_impact'], 2) }}</td>
                    <td>
                        @if($supplier['return_rate'] > 5)
                            <span class="warning">Perlu Evaluasi</span>
                        @else
                            Normal
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="summary">
        <h3>Ringkasan:</h3>
        <p>Total Supplier: {{ $data->count() }}</p>
        <p>Total Nilai Pembelian: Rp {{ number_format($data->sum('total_purchase_value')) }}</p>
        <p>Total Nilai Retur: Rp {{ number_format($data->sum('total_return_value')) }}</p>
        <p>Rata-rata Rate Retur: {{ number_format($data->avg('return_rate'), 2) }}%</p>
        <p>Supplier Berisiko (>5% return): {{ $data->where('return_rate', '>', 5)->count() }}</p>
    </div>

    <footer>
        <p>Generated by {{ config('app.name') }} on {{ now()->format('d-m-Y H:i:s') }}</p>
        <p>&copy; {{ date('Y') }} {{ config('app.name') }}. All rights reserved.</p>
    </footer>
</body>
</html>